version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: invoice_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  migration:
    build: .
    command: npm run migrate
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: example
      DB_NAME: invoice_db
    depends_on:
      - db
    networks:
      - backend

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: example
      DB_NAME: invoice_db
      ENV: DEV
    ports:
      - "3000:3000"
    depends_on:
      - migration
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge